[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lib_utils"
version = "0.1.0"
description = "Boîte à outils perso (gmail, etc.)"
requires-python = ">=3.9"
dependencies = [
    "python-dotenv>=1.0.0",
]

[tool.setuptools.packages.find]
include = ["lib_utils*"]
